### ISSUE TITLE
Go through add External Secrets to 'dependsOn'

### ISSUE THREAD

**Issue by binaryn3xus** [binaryn3xus/HomeOps#1009]
When I added the external secrets, i forgot to add the dependsOn for all the KS involved. I now have it in Gatus but it needs to be added to other places.

**Comment by binaryn3xus** [comment]
Added the following code to all KS.yaml files that have external secrets.

> Note: I did not add them to any that had volsync as a dependancy because volsync requires ESO before it can be up and running > anyways.

```yaml
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-azure
```
