### ISSUE TITLE
Setup SkyConnect 

### ISSUE THREAD

**Issue by binaryn3xus** [binaryn3xus/HomeOps#1262]
- [x] Actual own a zigbee device
- [x] Figure out device id for SkyConnect
- [x] Setup zigbee2mqtt (or something)
- [x] Test in Home Assistant

**Comment by binaryn3xus** [comment]
Device ID:

Command: `lsusb`
Result:
`Bus 001 Device 015: ID 10c4:ea60 Silicon Labs CP210x UART Bridge`

```yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/nodefeaturerules_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: skyconnect-zigbee-device
  rules:
    - # SkyConnect USB
      name: skyconnect.zigbee
      labels:
        skyconnect.feature.node.kubernetes.io/zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }
```
_Device class was zero or not set. Not sure why. We will try this way first._
